Update ru_RU.lang
GTNewHorizons/EnderIO pull request #48
Opened 2022-01-08 13:45 UTC by Zereff06

2022-01-08 15:59 UTC, TimeConqueror requested changes

2022-01-08 15:59 UTC, TimeConqueror commented on src/main/resources/assets/enderio/lang/ru_RU.lang
> +enderio.conductiveGrindingBall.name=Шарик соулария
соулария - soularium, явно не conductive сплав

2022-01-08 15:59 UTC, TimeConqueror commented on src/main/resources/assets/enderio/lang/ru_RU.lang
> +enderio.soulariumGrindingBall.name=Шарик призрачного металла
Soularium - определяемся какое название все таки юзать

2022-01-08 15:59 UTC, TimeConqueror commented on src/main/resources/assets/enderio/lang/ru_RU.lang
> +enderio.melodicAlloy.name=Медодичный сплав
Медодичный

2022-01-08 15:59 UTC, TimeConqueror commented on src/main/resources/assets/enderio/lang/ru_RU.lang
> +enderio.soulariumGrindingBall.name=Шарик призрачного металла
И если Призрачный сплав - то везде надо проверить и поправить

2022-01-08 15:59 UTC, TimeConqueror commented on src/main/resources/assets/enderio/lang/ru_RU.lang
> +enderio.precientPowder.name=Зерно предвидения
По названию powder - пыль, не знаю, как в игре, но вряд ли зерно.

2022-01-08 15:59 UTC, TimeConqueror commented on src/main/resources/assets/enderio/lang/ru_RU.lang
> +tile.blockSolarPanel.tooltip.detailed.line2=Должна иметь доступ к небу
Должна видеть небо

2022-01-08 15:59 UTC, TimeConqueror commented on src/main/resources/assets/enderio/lang/ru_RU.lang
> +enderio.stellarCapacitor.name=Звёздный Конденсатор
Конденсатор с маленькой буквы

2022-01-08 15:59 UTC, TimeConqueror commented on src/main/resources/assets/enderio/lang/ru_RU.lang
> +tile.blockEnderGenerator.name=Генератор Энда
Определяемся, где-то "Края", где-то "Энда"

2022-01-08 15:59 UTC, TimeConqueror commented on src/main/resources/assets/enderio/lang/ru_RU.lang
> +enderio.item.endSteel_sword.tooltip.line3=+2 Урон, при питании
при питании -> если запитан

2022-01-08 18:08 UTC, repo-alt commented on src/main/resources/assets/enderio/lang/ru_RU.lang
> +enderio.precientPowder.name=Пыль древнего кристалла
как ни странно в английском варианте это таки зёрна
enderio.pulsatingPowder.name=Grains of Piezallity
enderio.vibrantPowder.name=Grains of Vibrancy
enderio.enderCrystalPowder.name=Grains of the End
enderio.precientPowder.name=Grains of Prescience
хз как правильно

2022-01-09 06:31 UTC, repo-alt approved these changes

2022-01-10 11:46 UTC, merged